### ISSUE TITLE
how can I modify the width of a video clip?

### ISSUE THREAD

**Issue by zzm88** [mikeal/webtorrent-component#3]

**Comment by mikeal** [comment]
```css
web-torrent video {
  width: 400px;
}
```
